./testbackend_test.go:177:14: cannot use backend (type *testSystemBackend) as type podc.Backend in argument to New: 	*testSystemBackend does not implement podc.Backend (missing Multicast method)
; this error is solved by adding Multicast function ..